# Generated by Django 4.2.30 on 2026-07-08 09:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='timbre_fiscal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Calculé automatiquement sur HT+TVA (montant brut, déjà TTC) : ≤ 30 000 DA → 1% ; 30 000–100 000 DA → 1,5% ; ≥ 100 000 DA → 2%. Stocké pour les statistiques — n'affecte pas le coût total (`amount`).", max_digits=12, verbose_name='Timbre fiscal (DA)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='proof_document',
            field=models.FileField(blank=True, help_text='Reçu, avis de virement, copie de chèque, etc. (PDF, JPG, PNG).', null=True, upload_to='payment_proofs/%Y/%m/', verbose_name='Justificatif de paiement'),
        ),
    ]
